services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8800:80/tcp"
    environment:
      TZ: $TZ
      PROXY_LOCATION: pi.hole
      VIRTUAL_HOST: pi.hole
      WEBPASSWORD: joao123
    volumes:
      - '/home-data/containers-config/pihole/etc-pihole:/etc/pihole'
      - '/home-data/ontainers-config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped